### ISSUE TITLE
Could you resize the size of icon in inline code?

### ISSUE THREAD

**Issue by mzwlevi** [vyleung/logseq-copy-code-plugin#10]
The icon seems a little higher than the line height (with default theme)
![Screen Shot 2022-08-15 at 21 26 45](https://user-images.githubusercontent.com/78029539/184644260-8257a157-9d4f-42e3-90b2-ff192f06fdf3.png)
Thank you

**Comment by vyleung** [comment]
a workaround would be to copy and paste the following CSS in your custom.css file
```
.copy-button:hover {
    background-color: transparent;
}
```

does this work for you?

**Comment by mzwlevi** [comment]
> .copy-button:hover {
>     background-color: transparent;
> }
<img width="379" alt="Screen Shot 2022-08-16 at 02 14 52" src="https://user-images.githubusercontent.com/78029539/184692072-f6e19b2c-259e-4b14-9c00-fb68d67957f0.png">

It's Ok, Thank you for reply 🙏

**Comment by mzwlevi** [comment]
```css
.copy-button:hover {
    height: auto;
}
```
I have tried this code, the height of button was normal, but the height of inline code was strange

This is the video:


https://user-images.githubusercontent.com/78029539/184693795-c61d2430-f464-414c-8bda-cdf9aabe0495.mov

**Comment by mzwlevi** [comment]
> ```css
> .copy-button:hover {
>     height: auto;
> }
> ```
> 
> I have tried this code, the height of button was normal, but the height of inline code was strange
> 
> This is the video:
> 
>  Screen.Recording.2022-08-16.at.02.26.53.mov

```css
.copy-button {
    height: auto;
}
```
Fine, It's OK
