### ISSUE TITLE
Feature Request: Add option to always show copy icon

### ISSUE THREAD

**Issue by itsamemarkus** [vyleung/logseq-copy-code-plugin#11]
I use your awesome plugin for a lot of code snippets in my Logseq graph. Thank you. 

One thing that bugs me a little is that when the copy button appears all the other text jumps around, because the button is bigger than the text.

I'd love to have an option to always show the copy button, so that the whole page stays consistent when you hover over a code snippet.

https://user-images.githubusercontent.com/34944988/200890646-6dd537b8-a3b3-4049-8bc9-d927be782e8d.mp4

**Comment by vyleung** [comment]
hi, sorry for the late response! i've added this to v.1.2.0. can you update the plugin and check it out?

**Comment by itsamemarkus** [comment]
Thank you so much! (Required a restart to take effect) It's perfect!
