### ISSUE TITLE
Copy code button not appearing

### ISSUE THREAD

**Issue by AvijeetPrasad** [vyleung/logseq-copy-code-plugin#3]
Hi,

Thanks for this great plugin. I am really excited to use it, but unfortunately in my case the copy code button doesn't appear! I am attaching a screenshot and system details below. Can you please have a look?

- OS: macOS Monterey (12.3.1), Apple M1 Pro
- Logseq version: 0.6.8
- Copy Code: 1.0.1

![Screenshot 2022-05-14 at 07 01 21](https://user-images.githubusercontent.com/45669486/168411437-3760e078-5adf-4db2-b181-42973a0808ab.jpg)

I have tried the suggestions in your ReadMe of moving in and out of the block, but that doesn't seem to work for me.

**Comment by vyleung** [comment]
hi Avijeet! did you install the plugin via the marketplace? if so, this is a known issue (see #1). i've submitted a [pull request](https://github.com/logseq/marketplace/pull/177) to hopefully fix this issue.

as a workaround, please download [v.1.0.1](https://github.com/vyleung/logseq-copy-code-plugin/releases/tag/v.1.0.1) from github and load the plugin manually - let me know if the copy code button appears using this method

**Comment by AvijeetPrasad** [comment]
Hi!

Thanks for your reply. I loaded the plugin manually, and it works quite well that way 😀

**Comment by vyleung** [comment]
please try re-installing the plugin via the marketplace - it should work normally now

**Comment by AvijeetPrasad** [comment]
I installed the updated version from the marketplace now. It is working fine 😀 👍🏼

**Comment by vyleung** [comment]
happy to hear that!
