### ISSUE TITLE
FR: copy code option for inline code blocks

### ISSUE THREAD

**Issue by AvijeetPrasad** [vyleung/logseq-copy-code-plugin#4]
Hi,

Thanks for the great plugin, which is super-useful. I was thinking whether it would be possible to have an option for copying inline code blocks as well? 

One use case could be copying `file:///a very long pathname that I wrote inline`. The copy button in this case need not be always present, but can be triggered by a shortcut. That way, it won't affect the readability of the text under normal usage. It would still be quite faster than going into the edit mode of a block and copying the whole text.

**Comment by vyleung** [comment]
hi Avijeet, thanks for the feature request! what are your thoughts on showing a copy code button when hovering over the inline code (see demo) compared to using a keyboard shortcut?

https://user-images.githubusercontent.com/64292157/169439032-932581d3-ad16-4bfa-ac89-b47cee3565e5.mp4

**Comment by AvijeetPrasad** [comment]
Hi!

This looks great 👏 I think show on hover is more natural and convenient to use as compared to a keyboard shortcut. So I would say the current implementation is perfect 😀

**Comment by vyleung** [comment]
this feature has been added in [v.1.1.0](https://github.com/vyleung/logseq-copy-code-plugin/releases/tag/v.1.1.0) - please refresh Logseq after updating the plugin via the marketplace

let me know if you run into any issues

**Comment by AvijeetPrasad** [comment]
I updated to v.1.1.0. It's working great!

**Comment by vyleung** [comment]
glad to hear that!
