### ISSUE TITLE
copy-code version problem

### ISSUE THREAD

**Issue by lion-no-back** [vyleung/logseq-copy-code-plugin#6]
Hello, I have benefited a lot from your Helium plugin, and I also like your other Copy Code plugin, but what is confusing is that my version 1.0.1 is available and the rest, including today's update, are invalid. My operating system is win11. Thank you for the development of the logseq plugin 

https://user-images.githubusercontent.com/100990301/169517880-b6f53122-c1d4-4a0e-82b5-0549b443ddd6.mp4

**Comment by AvijeetPrasad** [comment]
Hi, even I am facing a similar issue that in version `1.1.0`, while the inline code copy is working perfectly, it is no longer able to copy from the source code blocks. I am using macOS 12 with Logseq `0.6.9`.

**Comment by vyleung** [comment]
sorry for the inconvenience! i’ll work on fixing this issue ASAP

**Comment by vyleung** [comment]
the bug was a small typo 😅 - this issue should be fixed in [v.1.1.1](https://github.com/vyleung/logseq-copy-code-plugin/releases/tag/v.1.1.1)

**Comment by AvijeetPrasad** [comment]
Works well with `v1.1.1` 👍🏼

**Comment by vyleung** [comment]
happy to hear that 🙂
