### ISSUE TITLE
Is the plugin working for the latest version of Logseq?

### ISSUE THREAD

**Issue by AhmedThahir** [vyleung/logseq-copy-code-plugin#8]
Hi
I tried both refreshing, re-indexing as well as restarting, but the plugin doesn't seem to work.

**Comment by vyleung** [comment]
hi Ahmed - i'm on version 0.7.6, and it's working for me. 

can you open dev tools (Mac: cmd+option+i | Windows: ctrl+shift+i) and see if there are any errors when you install the plugin?

**Comment by AhmedThahir** [comment]
I was just testing moving around the icon. Weirdly the plugin works now that I've moved it inside the code block section, using the settings.
